
mobile_net_model:
  MOBILE_IMG_SHAPE : [224,224,3]
  MOBILE_DROP_LAYERS : -5
  MOBILE_TRAINABLE_LAYERS : 70
  MOBILE_EPOCHS : 70
  MOBILE_VERBOSE : 1
  MOBILE_BATCH_SIZE : 16
  TRAIN_MOBILE : False

effnet_model:
  EFFNET_IMG_SHAPE : [224,224,3]
  EFFNET_EPOCHS : 50
  EFFNET_VERBOSE : 1
  EFFNET_BATCH_SIZE : 16
  TRAIN_EFFNET : False

custom_model:
  CUSTOM_IMG_SHAPE : [96, 96, 1]
  CUSTOM_EPOCHS : 70
  CUSTOM_VERBOSE : 1
  CUSTOM_BATCH_SIZE : 16
  TRAIN_CUSTOM : False
