name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**/*.md', '**/README*' ]
  workflow_dispatch:

jobs:
  ci-tests:
    name: Test, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Unit tests (model)
        env: { DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} }
        run: python -m unittest tests/test_model.py

      - name: Unit tests (flask)
        env: { DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} }
        run: python -m unittest tests/test_flask_app.py

      - name: Promote model to production
        env: { DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} }
        run: python scripts/promote_model.py

      # AWS creds for ECR + EKS (must match the IAM principal you gave access to the cluster)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # Ensure ECR repo exists
      - name: Ensure ECR repository
        run: |
          aws ecr describe-repositories --repository-names "${{ secrets.ECR_REPOSITORY }}" \
          || aws ecr create-repository --repository-name "${{ secrets.ECR_REPOSITORY }}"

      # Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build & push image (tag with SHA and latest)
      - name: Build & push Docker image
        env:
          IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        run: |
          docker build -t "$IMAGE_URI:latest" -t "$IMAGE_URI:${{ github.sha }}" .
          docker push "$IMAGE_URI:${{ github.sha }}"
          docker push "$IMAGE_URI:latest"

      # kubectl
      - name: Set Up kubectl
        uses: azure/setup-kubectl@v3
        with: { version: 'latest' }

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name flask-app-cluster

      # Create/Update Secret that app expects
      - name: Create/Update Kubernetes Secret
        run: |
          kubectl create secret generic dagshub-secret \
            --from-literal=DAGSHUB_TOKEN='${{ secrets.DAGSHUB_TOKEN }}' \
            --dry-run=client -o yaml | kubectl apply -f -

      # Apply manifests, set image to this commit, wait longer for rollout
      - name: Deploy to EKS
        env:
          IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
        run: |
          kubectl apply -f deployment.yaml
          kubectl set image deployment/flask-app flask-app="$IMAGE_URI:${{ github.sha }}"
          kubectl rollout status deployment/flask-app --timeout=20m
